service: sls-rekognition-compare-base64 

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1 # Nearest AZ to offer rekognition is Tokyo  
  deploymentBucket: my-serverless-projects-ap-northeast-1  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync        
      Resource: "arn:aws:lambda:ap-northeast-1:*:*:*"  
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"             

functions:
  compareFacesBase64:
    handler: handler.compareFacesBase64
    events:
    - http:
        path: compare-faces-base64
        method: post    