service: aws-lambda-node-upload-to-s3

custom:
  bucket: my-serverless-projects/test-s3-upload

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-1  
  deploymentBucket: my-serverless-projects
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync        
      Resource: "arn:aws:lambda:ap-southeast-1:*:*:*"  
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  uploadToS3:
    handler: handler.uploadToS3
    environment:
      BUCKET: ${self:custom.bucket}    
    events:
    - http:
        path: uploadToS3
        method: post
